#!/usr/bin/env python3
"""Generate a stock-grounded proprietary-files seed for T65 Max.

The reference file supplies categories and likely MT6789 blob names only. A
line is emitted exclusively when its source path exists in the rooted stock
file inventory. No binary is copied from the reference device.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def source_path(line: str) -> str | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    stripped = stripped.lstrip("-")
    source = stripped.split(";", 1)[0].split(":", 1)[0]
    return source.removeprefix("/")


def read_inventory(paths: list[Path]) -> set[str]:
    result: set[str] = set()
    for path in paths:
        for line in path.read_text(encoding="utf-8").splitlines():
            item = line.strip().removeprefix("/")
            if item:
                result.add(item)
    return result


def filtered_blocks(reference: Path, inventory: set[str]) -> list[str]:
    blocks = reference.read_text(encoding="utf-8").split("\n\n")
    output: list[str] = []
    for block in blocks:
        lines = block.splitlines()
        blobs = [line for line in lines if source_path(line) in inventory]
        if not blobs:
            continue
        comments = [line for line in lines if line.strip().startswith("#")]
        output.extend(comments)
        output.extend(blobs)
        output.append("")
    return output


def candidate_paths(inventory: set[str], selected: set[str]) -> list[str]:
    prefixes = (
        "vendor/bin/hw/",
        "vendor/etc/audio_param/",
        "vendor/etc/firmware/",
        "vendor/etc/init/",
        "vendor/etc/vintf/",
        "vendor/firmware/",
        "vendor/lib/hw/",
        "vendor/lib/mt6789/",
        "vendor/lib64/hw/",
        "vendor/lib64/mt6789/",
    )
    return sorted(path for path in inventory if path.startswith(prefixes) and path not in selected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference", type=Path, required=True)
    parser.add_argument("--inventory", type=Path, action="append", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--candidates", type=Path, required=True)
    args = parser.parse_args()

    inventory = read_inventory(args.inventory)
    body = filtered_blocks(args.reference, inventory)
    selected = {path for line in body if (path := source_path(line)) is not None}

    header = [
        "# Teclast T65 Max A8D3 hardware running official A8D4 ROW Android 15",
        "# Stock base: T65Max(A8D4)_Android 15_V1.07_20250603_ROW_SZ",
        "# Generated by intersecting an MT6789 category reference with the",
        "# rooted stock file inventory. Binary content must come from this tablet",
        "# or the matching official A8D4 firmware, never from the reference device.",
        "# WIP: device-specific candidates still require manual curation.",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(header + body).rstrip() + "\n", encoding="utf-8")

    candidates = candidate_paths(inventory, selected)
    args.candidates.parent.mkdir(parents=True, exist_ok=True)
    args.candidates.write_text("\n".join(candidates) + "\n", encoding="utf-8")

    print(f"selected={len(selected)} candidates={len(candidates)}")


if __name__ == "__main__":
    main()
